name: Update GeoX

on:
  schedule:
    - cron: "0 0 * * *" # 每天执行一次
  workflow_dispatch:

permissions:
  contents: write   # ✅ 必须添加，否则 403

jobs:
  update-geox:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}  # 默认内置的 token

      - name: Download GeoX files
        run: |
          mkdir -p geox
          curl -L -o geox/GeoIP.dat https://github.com/Loyalsoldier/v2ray-rules-dat/releases/latest/download/geoip.dat
          curl -L -o geox/GeoSite.dat https://github.com/Loyalsoldier/v2ray-rules-dat/releases/latest/download/geosite.dat
          curl -L -o geox/GeoLite2-ASN.mmdb https://github.com/Loyalsoldier/geoip/releases/latest/download/GeoLite2-ASN.mmdb
          curl -L -o geox/geoip-lite.dat https://github.com/MetaCubeX/meta-rules-dat/releases/latest/download/geoip-lite.dat
          curl -L -o geox/geoip-lite.metadb https://github.com/MetaCubeX/meta-rules-dat/releases/latest/download/geoip-lite.metadb
          curl -L -o geox/geosite.dat https://github.com/MetaCubeX/meta-rules-dat/releases/latest/download/geosite.dat

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add geox/*
          git commit -m "Update GeoX files" || echo "No changes to commit"
          git push
